missing parameter for key "Adj Close"
KeyError: "Adj Close" when ran in pytest
https://github.com/ranaroussi/yfinance/wiki/Ticker
just added missing parameter for this key.